// data file for App 14: Doors

var subjectInfo = [
// subject name, page title, type, array, image-folder, array-name, index row title, index row image, mapImage, hasMultipleImages
	[ "WhatIs", "What is Q2A ?", "n", "da1", "", "da1", "What is Q2A ?", "QuestionMark", "", "" ],
	[ "HowTo", "How To Use Q2A", "n", "da2", "", "da2", "How To Use Q2A", "QuestionMark", "", "" ],
	[ "DoorsianToEnglish", "Doorsian to English", "a", "da3", "", "da3", "Doorsian to English List", "QuestionMark", "", "False" ],
	[ "EnglishToDoorsian", "English to Doorsian", "s", "da4", "", "da4", "English to Doorsian List", "QuestionMark", "", "False" ],
	[ "Doorsian", "Doorsian Language", "t", "da5", "", "da5", "Doorsian Language", "QuestionMark", "", "False" ]
];

var da1 = [
"<p>Q2A is a family of learning apps, using questions with multiple choice answers.</p><p>Some apps are free, others have a small cost.</p><p>Each app has a number of <b>subjects</b>, and each subject has a number of <b>questions</b>.</p><p>Current apps are:<br/>Air - aviation subjects<br/>Flags - flags of countries, counties ...<br/>French - towns, province flags ...<br/>Geo - geographical, locations of places ...<br/>Sampler - a selection of subject subsets from other apps</p>"
];

var da2 = [
"<p>When you select a subject, the app runs a session of 10 questions, randomly chosen. <br /> Each question appears with 3 possible answers, one correct and two randomly chosen wrong answers.</p><p>If you select the correct answer immediately, a progress indicator shows green, and presents the next question. <br /> The indicator shows red if wrong, and waits for another selection. <br />When a wrong answer is corrected, the indicator remains red.</p><p>After 10 questions, a score is displayed, based on the time taken and the number of retries.<br />When you click the score panel, another session begins.</p>"
];

var da3 = [
	[ "(t)zay", "thank you", "1" ],
	[ "a", "one", "1" ],
	[ "a'", "at / have/ zai / on", "1" ],
	[ "abay", "direction/way", "1" ],
	[ "a'dam", "place", "1" ],
	[ "a'doh", "together", "1" ],
	[ "adoh (like add on)", "more", "1" ],
	[ "adon", "extension", "1" ],
	[ "aff", "happiness", "1" ],
	[ "aff", "joy", "1" ],
	[ "aga", "against", "1" ],
	[ "aida", "help", "1" ],
	[ "air(ghgh)", "see", "1" ],
	[ "airth", "beginning", "1" ],
	[ "anof", "feel", "1" ],
	[ "ar", "reach", "1" ],
	[ "ash", "zero", "1" ],
	[ "asoo", "move", "1" ],
	[ "aven", "dwell", "1" ],
	[ "aves", "life", "1" ],
	[ "awa", "everything", "1" ],
	[ "awa", "all / every / everyone", "1" ],
	[ "awas", "always", "1" ],
	[ "awool", "whole", "1" ],
	[ "awoosk", "world / universe", "1" ],
	[ "b'airth", "come from", "1" ],
	[ "b'airth", "creation", "1" ],
	[ "ban", "take (ba3)", "1" ],
	[ "bess", "reality", "1" ],
	[ "boo-a", "maybe", "1" ],
	[ "boon", "part", "1" ],
	[ "chewn (chewn)", "eat", "1" ],
	[ "co", "small", "1" ],
	[ "coht", "same", "1" ],
	[ "coo", "how", "1" ],
	[ "cosh", "safe", "1" ],
	[ "dama", "put away", "1" ],
	[ "dana", "lost", "1" ],
	[ "daween", "change", "1" ],
	[ "de", "and then", "1" ],
	[ "deem", "like", "1" ],
	[ "den", "thing / essence", "1" ],
	[ "dena", "If not", "1" ],
	[ "desha", "long / lots", "1" ],
	[ "Diet", "people / beings", "1" ],
	[ "doh", "or", "1" ],
	[ "doh", "two", "1" ],
	[ "don?", "where?", "1" ],
	[ "doon", "wait", "1" ],
	[ "doon", "deep", "1" ],
	[ "dusa", "dust", "1" ],
	[ "dut", "end", "1" ],
	[ "dway", "treat (dui4)", "1" ],
	[ "edos", "obsolete", "1" ],
	[ "eesh", "infinity", "1" ],
	[ "e-esht", "itself / theirselves", "1" ],
	[ "eev", "if", "1" ],
	[ "Eh2", "come", "1" ],
	[ "ehwool", "let go", "1" ],
	[ "eka", "before", "1" ],
	[ "e'kwuun", "understand", "1" ],
	[ "elit", "describe", "1" ],
	[ "ema", "meaning", "1" ],
	[ "en", "day", "1" ],
	[ "espa", "spirits", "1" ],
	[ "far(gh)", "material", "1" ],
	[ "gaw", "tell", "1" ],
	[ "gege", "again / repeat", "1" ],
	[ "geh", "let's", "1" ],
	[ "Geyan", "tangible", "1" ],
	[ "goll zesh", "give birth", "1" ],
	[ "goll(ort)", "give", "1" ],
	[ "gor-yan", "dark", "1" ],
	[ "gun", "too", "1" ],
	[ "gun", "very", "1" ],
	[ "g'yan", "fear", "1" ],
	[ "ha-ay", "possible", "1" ],
	[ "hay", "can (ability)", "1" ],
	[ "hay", "still", "1" ],
	[ "how(t) nine", "good night", "1" ],
	[ "howth", "good", "1" ],
	[ "iiiss", "fascinating", "1" ],
	[ "il", "enough", "1" ],
	[ "inos", "inside / within", "1" ],
	[ "inos", "within/inside", "1" ],
	[ "jar", "belong", "1" ],
	[ "jee", "by / from", "1" ],
	[ "jee-er", "wonderful", "1" ],
	[ "k’", "from", "1" ],
	[ "kai", "why?", "1" ],
	[ "kawarith", "eternal", "1" ],
	[ "kawarith", "mysterious thing", "1" ],
	[ "keet", "remember", "1" ],
	[ "keloonet", "objective", "1" ],
	[ "kep", "now", "1" ],
	[ "ket", "this", "1" ],
	[ "keta", "that", "1" ],
	[ "ketong", "disappear", "1" ],
	[ "kez'tha", "cat", "1" ],
	[ "kide", "edge", "1" ],
	[ "kinta", "bless", "1" ],
	[ "kireen", "beautiful", "1" ],
	[ "kitay", "imagine", "1" ],
	[ "kon", "here", "1" ],
	[ "kon", "say", "1" ],
	[ "kona", "there", "1" ],
	[ "ku", "as", "1" ],
	[ "kun", "but", "1" ],
	[ "kung", "become", "1" ],
	[ "kwuun", "think", "1" ],
	[ "kyo", "today", "1" ],
	[ "la-eyn", "tired", "1" ],
	[ "lang", "way (yang4zi)", "1" ],
	[ "langoh", "corridor", "1" ],
	[ "layg", "fit", "1" ],
	[ "laysht", "put (to be)", "1" ],
	[ "lutayboo", "what's wrong?", "1" ],
	[ "meeng", "mind", "1" ],
	[ "min", "door", "1" ],
	[ "miranka", "forever", "1" ],
	[ "mirutay", "find / search / look", "1" ],
	[ "mirutay", "look / find / search", "1" ],
	[ "moy", "soup", "1" ],
	[ "n'adoh", "separate", "1" ],
	[ "naysht", "existence", "1" ],
	[ "nea", "close", "1" ],
	[ "nec", "new", "1" ],
	[ "neda", "never", "1" ],
	[ "nesta", "has to (what it had to)", "1" ],
	[ "nnn", "try", "1" ],
	[ "no-eesh", "finite", "1" ],
	[ "noh", "not", "1" ],
	[ "noh estek", "intangible", "1" ],
	[ "nohden", "nothing", "1" ],
	[ "noo-t", "different", "1" ],
	[ "ol", "loop", "1" ],
	[ "ool", "look  (at that!)", "1" ],
	[ "oon", "hungry", "1" ],
	[ "oss", "strong", "1" ],
	[ "pa", "grandpa", "1" ],
	[ "piesk", "glimmer", "1" ],
	[ "pon", "already", "1" ],
	[ "poont", "must", "1" ],
	[ "por", "for", "1" ],
	[ "pun", "only", "1" ],
	[ "ray'en", "reason", "1" ],
	[ "rekoot", "explain", "1" ],
	[ "rletta", "escape", "1" ],
	[ "san", "soul", "1" ],
	[ "sanooth", "consciousness", "1" ],
	[ "sareen", "happy", "1" ],
	[ "seemkwa", "know", "1" ],
	[ "seemkwan", "known", "1" ],
	[ "sepa", "another", "1" ],
	[ "shakay", "shadows", "1" ],
	[ "she-een", "heart", "1" ],
	[ "shen", "appear / show up", "1" ],
	[ "sheshte", "protect", "1" ],
	[ "sh'yan", "outside", "1" ],
	[ "sin", "because", "1" ],
	[ "skess skess", "draw", "1" ],
	[ "s-ku", "grow", "1" ],
	[ "solu", "trust", "1" ],
	[ "son?", "what?", "1" ],
	[ "soo", "who?", "1" ],
	[ "sool", "to be*", "1" ],
	[ "sootay", "rest", "1" ],
	[ "sueth", "clear", "1" ],
	[ "sulee", "on own", "1" ],
	[ "tabay", "many / much", "1" ],
	[ "tahnk", "upstairs", "1" ],
	[ "tak", "allow", "1" ],
	[ "ta'k-ray", "wall", "1" ],
	[ "tan", "with (gen)", "1" ],
	[ "tata", "good boy", "1" ],
	[ "tay", "pardon", "1" ],
	[ "tay(4)", "stay", "1" ],
	[ "tayboo", "wrong", "1" ],
	[ "teeng", "hear", "1" ],
	[ "tem", "time", "1" ],
	[ "terra", "compared", "1" ],
	[ "Teth", "faith / belief", "1" ],
	[ "the-een", "centre", "1" ],
	[ "thoon", "pray", "1" ],
	[ "thoona", "prayer", "1" ],
	[ "tor", "far", "1" ],
	[ "tuu-ee", "also", "1" ],
	[ "twe", "do", "1" ],
	[ "tzair (qie)", "please", "1" ],
	[ "vay", "true true", "1" ],
	[ "vay", "truth", "1" ],
	[ "we", "will (of god)", "1" ],
	[ "wilis", "dimensions", "1" ],
	[ "yada", "shelter", "1" ],
	[ "yan", "evils / those outside", "1" ],
	[ "yat", "yes", "1" ],
	[ "yeness", "originally", "1" ],
	[ "you", "need", "1" ],
	[ "you", "go", "1" ],
	[ "you-een", "stray", "1" ],
	[ "yurn", "want", "1" ],
	[ "yuss", "have", "1" ],
	[ "zar", "every / each", "1" ],
	[ "zell", "words", "1" ],
	[ "zetheen", "wish", "1" ],
	[ "zong-ut", "important", "1" ],
	[ "zos", "drift", "1" ]
];

var da4 = [
	[ "again / repeat", "gege", "1" ],
	[ "against", "aga", "1" ],
	[ "all / every / everyone", "awa", "1" ],
	[ "allow", "tak", "1" ],
	[ "already", "pon", "1" ],
	[ "also", "tuu-ee", "1" ],
	[ "always", "awas", "1" ],
	[ "and then", "de", "1" ],
	[ "another", "sepa", "1" ],
	[ "appear / show up", "shen", "1" ],
	[ "as", "ku", "1" ],
	[ "at / have/ zai / on", "a'", "1" ],
	[ "beautiful", "kireen", "1" ],
	[ "because", "sin", "1" ],
	[ "become", "kung", "1" ],
	[ "before", "eka", "1" ],
	[ "beginning", "airth", "1" ],
	[ "belong", "jar", "1" ],
	[ "bless", "kinta", "1" ],
	[ "but", "kun", "1" ],
	[ "by / from", "jee", "1" ],
	[ "can (ability)", "hay", "1" ],
	[ "cat", "kez'tha", "1" ],
	[ "centre", "the-een", "1" ],
	[ "change", "daween", "1" ],
	[ "clear", "sueth", "1" ],
	[ "close", "nea", "1" ],
	[ "come", "Eh2", "1" ],
	[ "come from", "b'airth", "1" ],
	[ "compared", "terra", "1" ],
	[ "consciousness", "sanooth", "1" ],
	[ "corridor", "langoh", "1" ],
	[ "creation", "b'airth", "1" ],
	[ "dark", "gor-yan", "1" ],
	[ "day", "en", "1" ],
	[ "deep", "doon", "1" ],
	[ "describe", "elit", "1" ],
	[ "different", "noo-t", "1" ],
	[ "dimensions", "wilis", "1" ],
	[ "direction/way", "abay", "1" ],
	[ "disappear", "ketong", "1" ],
	[ "do", "twe", "1" ],
	[ "door", "min", "1" ],
	[ "draw", "skess skess", "1" ],
	[ "drift", "zos", "1" ],
	[ "dust", "dusa", "1" ],
	[ "dwell", "aven", "1" ],
	[ "eat", "chewn (chewn)", "1" ],
	[ "edge", "kide", "1" ],
	[ "end", "dut", "1" ],
	[ "enough", "il", "1" ],
	[ "escape", "rletta", "1" ],
	[ "eternal", "kawarith", "1" ],
	[ "every / each", "zar", "1" ],
	[ "everything", "awa", "1" ],
	[ "evils / those outside", "yan", "1" ],
	[ "existence", "naysht", "1" ],
	[ "explain", "rekoot", "1" ],
	[ "extension", "adon", "1" ],
	[ "faith / belief", "Teth", "1" ],
	[ "far", "tor", "1" ],
	[ "fascinating", "iiiss", "1" ],
	[ "fear", "g'yan", "1" ],
	[ "feel", "anof", "1" ],
	[ "find / search / look", "mirutay", "1" ],
	[ "finite", "no-eesh", "1" ],
	[ "fit", "layg", "1" ],
	[ "for", "por", "1" ],
	[ "forever", "miranka", "1" ],
	[ "from", "k’", "1" ],
	[ "give", "goll(ort)", "1" ],
	[ "give birth", "goll zesh", "1" ],
	[ "glimmer", "piesk", "1" ],
	[ "go", "you", "1" ],
	[ "good", "howth", "1" ],
	[ "good boy", "tata", "1" ],
	[ "good night", "how(t) nine", "1" ],
	[ "grandpa", "pa", "1" ],
	[ "grow", "s-ku", "1" ],
	[ "happiness", "aff", "1" ],
	[ "happy", "sareen", "1" ],
	[ "has to (what it had to)", "nesta", "1" ],
	[ "have", "yuss", "1" ],
	[ "hear", "teeng", "1" ],
	[ "heart", "she-een", "1" ],
	[ "help", "aida", "1" ],
	[ "here", "kon", "1" ],
	[ "how", "coo", "1" ],
	[ "hungry", "oon", "1" ],
	[ "if", "eev", "1" ],
	[ "If not", "dena", "1" ],
	[ "imagine", "kitay", "1" ],
	[ "important", "zong-ut", "1" ],
	[ "infinity", "eesh", "1" ],
	[ "inside / within", "inos", "1" ],
	[ "intangible", "noh estek", "1" ],
	[ "itself / theirselves", "e-esht", "1" ],
	[ "joy", "aff", "1" ],
	[ "know", "seemkwa", "1" ],
	[ "known", "seemkwan", "1" ],
	[ "let go", "ehwool", "1" ],
	[ "let's", "geh", "1" ],
	[ "life", "aves", "1" ],
	[ "like", "deem", "1" ],
	[ "long / lots", "desha", "1" ],
	[ "look  (at that!)", "ool", "1" ],
	[ "look / find / search", "mirutay", "1" ],
	[ "loop", "ol", "1" ],
	[ "lost", "dana", "1" ],
	[ "many / much", "tabay", "1" ],
	[ "material", "far(gh)", "1" ],
	[ "maybe", "boo-a", "1" ],
	[ "meaning", "ema", "1" ],
	[ "mind", "meeng", "1" ],
	[ "more", "adoh (like add on)", "1" ],
	[ "move", "asoo", "1" ],
	[ "must", "poont", "1" ],
	[ "mysterious thing", "kawarith", "1" ],
	[ "need", "you", "1" ],
	[ "never", "neda", "1" ],
	[ "new", "nec", "1" ],
	[ "not", "noh", "1" ],
	[ "nothing", "nohden", "1" ],
	[ "now", "kep", "1" ],
	[ "objective", "keloonet", "1" ],
	[ "obsolete", "edos", "1" ],
	[ "on own", "sulee", "1" ],
	[ "one", "a", "1" ],
	[ "only", "pun", "1" ],
	[ "or", "doh", "1" ],
	[ "originally", "yeness", "1" ],
	[ "outside", "sh'yan", "1" ],
	[ "pardon", "tay", "1" ],
	[ "part", "boon", "1" ],
	[ "people / beings", "Diet", "1" ],
	[ "place", "a'dam", "1" ],
	[ "please", "tzair (qie)", "1" ],
	[ "possible", "ha-ay", "1" ],
	[ "pray", "thoon", "1" ],
	[ "prayer", "thoona", "1" ],
	[ "protect", "sheshte", "1" ],
	[ "put (to be)", "laysht", "1" ],
	[ "put away", "dama", "1" ],
	[ "reach", "ar", "1" ],
	[ "reality", "bess", "1" ],
	[ "reason", "ray'en", "1" ],
	[ "remember", "keet", "1" ],
	[ "rest", "sootay", "1" ],
	[ "safe", "cosh", "1" ],
	[ "same", "coht", "1" ],
	[ "say", "kon", "1" ],
	[ "see", "air(ghgh)", "1" ],
	[ "separate", "n'adoh", "1" ],
	[ "shadows", "shakay", "1" ],
	[ "shelter", "yada", "1" ],
	[ "small", "co", "1" ],
	[ "soul", "san", "1" ],
	[ "soup", "moy", "1" ],
	[ "spirits", "espa", "1" ],
	[ "stay", "tay(4)", "1" ],
	[ "still", "hay", "1" ],
	[ "stray", "you-een", "1" ],
	[ "strong", "oss", "1" ],
	[ "take (ba3)", "ban", "1" ],
	[ "tangible", "Geyan", "1" ],
	[ "tell", "gaw", "1" ],
	[ "thank you", "(t)zay", "1" ],
	[ "that", "keta", "1" ],
	[ "there", "kona", "1" ],
	[ "thing / essence", "den", "1" ],
	[ "think", "kwuun", "1" ],
	[ "this", "ket", "1" ],
	[ "time", "tem", "1" ],
	[ "tired", "la-eyn", "1" ],
	[ "to be*", "sool", "1" ],
	[ "today", "kyo", "1" ],
	[ "together", "a'doh", "1" ],
	[ "too", "gun", "1" ],
	[ "treat (dui4)", "dway", "1" ],
	[ "true true", "vay", "1" ],
	[ "trust", "solu", "1" ],
	[ "truth", "vay", "1" ],
	[ "try", "nnn", "1" ],
	[ "two", "doh", "1" ],
	[ "understand", "e'kwuun", "1" ],
	[ "upstairs", "tahnk", "1" ],
	[ "very", "gun", "1" ],
	[ "wait", "doon", "1" ],
	[ "wall", "ta'k-ray", "1" ],
	[ "want", "yurn", "1" ],
	[ "way (yang4zi)", "lang", "1" ],
	[ "what?", "son?", "1" ],
	[ "what's wrong?", "lutayboo", "1" ],
	[ "where?", "don?", "1" ],
	[ "who?", "soo", "1" ],
	[ "whole", "awool", "1" ],
	[ "why?", "kai", "1" ],
	[ "will (of god)", "we", "1" ],
	[ "wish", "zetheen", "1" ],
	[ "with (gen)", "tan", "1" ],
	[ "within/inside", "inos", "1" ],
	[ "wonderful", "jee-er", "1" ],
	[ "words", "zell", "1" ],
	[ "world / universe", "awoosk", "1" ],
	[ "wrong", "tayboo", "1" ],
	[ "yes", "yat", "1" ],
	[ "zero", "ash", "1" ]
];

var da5 = [
	[ "again / repeat", "gege", "1" ],
	[ "against", "aga", "1" ],
	[ "all / every / everyone", "awa", "1" ],
	[ "allow", "tak", "1" ],
	[ "already", "pon", "1" ],
	[ "also", "tuu-ee", "1" ],
	[ "always", "awas", "1" ],
	[ "and then", "de", "1" ],
	[ "another", "sepa", "1" ],
	[ "appear / show up", "shen", "1" ],
	[ "as", "ku", "1" ],
	[ "at / have/ zai / on", "a'", "1" ],
	[ "beautiful", "kireen", "1" ],
	[ "because", "sin", "1" ],
	[ "become", "kung", "1" ],
	[ "before", "eka", "1" ],
	[ "beginning", "airth", "1" ],
	[ "belong", "jar", "1" ],
	[ "bless", "kinta", "1" ],
	[ "but", "kun", "1" ],
	[ "by / from", "jee", "1" ],
	[ "can (ability)", "hay", "1" ],
	[ "cat", "kez'tha", "1" ],
	[ "centre", "the-een", "1" ],
	[ "change", "daween", "1" ],
	[ "clear", "sueth", "1" ],
	[ "close", "nea", "1" ],
	[ "come", "Eh2", "1" ],
	[ "come from", "b'airth", "1" ],
	[ "compared", "terra", "1" ],
	[ "consciousness", "sanooth", "1" ],
	[ "corridor", "langoh", "1" ],
	[ "creation", "b'airth", "1" ],
	[ "dark", "gor-yan", "1" ],
	[ "day", "en", "1" ],
	[ "deep", "doon", "1" ],
	[ "describe", "elit", "1" ],
	[ "different", "noo-t", "1" ],
	[ "dimensions", "wilis", "1" ],
	[ "direction/way", "abay", "1" ],
	[ "disappear", "ketong", "1" ],
	[ "do", "twe", "1" ],
	[ "door", "min", "1" ],
	[ "draw", "skess skess", "1" ],
	[ "drift", "zos", "1" ],
	[ "dust", "dusa", "1" ],
	[ "dwell", "aven", "1" ],
	[ "eat", "chewn (chewn)", "1" ],
	[ "edge", "kide", "1" ],
	[ "end", "dut", "1" ],
	[ "enough", "il", "1" ],
	[ "escape", "rletta", "1" ],
	[ "eternal", "kawarith", "1" ],
	[ "every / each", "zar", "1" ],
	[ "everything", "awa", "1" ],
	[ "evils / those outside", "yan", "1" ],
	[ "existence", "naysht", "1" ],
	[ "explain", "rekoot", "1" ],
	[ "extension", "adon", "1" ],
	[ "faith / belief", "Teth", "1" ],
	[ "far", "tor", "1" ],
	[ "fascinating", "iiiss", "1" ],
	[ "fear", "g'yan", "1" ],
	[ "feel", "anof", "1" ],
	[ "find / search / look", "mirutay", "1" ],
	[ "finite", "no-eesh", "1" ],
	[ "fit", "layg", "1" ],
	[ "for", "por", "1" ],
	[ "forever", "miranka", "1" ],
	[ "from", "k’", "1" ],
	[ "give", "goll(ort)", "1" ],
	[ "give birth", "goll zesh", "1" ],
	[ "glimmer", "piesk", "1" ],
	[ "go", "you", "1" ],
	[ "good", "howth", "1" ],
	[ "good boy", "tata", "1" ],
	[ "good night", "how(t) nine", "1" ],
	[ "grandpa", "pa", "1" ],
	[ "grow", "s-ku", "1" ],
	[ "happiness", "aff", "1" ],
	[ "happy", "sareen", "1" ],
	[ "has to (what it had to)", "nesta", "1" ],
	[ "have", "yuss", "1" ],
	[ "hear", "teeng", "1" ],
	[ "heart", "she-een", "1" ],
	[ "help", "aida", "1" ],
	[ "here", "kon", "1" ],
	[ "how", "coo", "1" ],
	[ "hungry", "oon", "1" ],
	[ "if", "eev", "1" ],
	[ "If not", "dena", "1" ],
	[ "imagine", "kitay", "1" ],
	[ "important", "zong-ut", "1" ],
	[ "infinity", "eesh", "1" ],
	[ "inside / within", "inos", "1" ],
	[ "intangible", "noh estek", "1" ],
	[ "itself / theirselves", "e-esht", "1" ],
	[ "joy", "aff", "1" ],
	[ "know", "seemkwa", "1" ],
	[ "known", "seemkwan", "1" ],
	[ "let go", "ehwool", "1" ],
	[ "let's", "geh", "1" ],
	[ "life", "aves", "1" ],
	[ "like", "deem", "1" ],
	[ "long / lots", "desha", "1" ],
	[ "look  (at that!)", "ool", "1" ],
	[ "look / find / search", "mirutay", "1" ],
	[ "loop", "ol", "1" ],
	[ "lost", "dana", "1" ],
	[ "many / much", "tabay", "1" ],
	[ "material", "far(gh)", "1" ],
	[ "maybe", "boo-a", "1" ],
	[ "meaning", "ema", "1" ],
	[ "mind", "meeng", "1" ],
	[ "more", "adoh (like add on)", "1" ],
	[ "move", "asoo", "1" ],
	[ "must", "poont", "1" ],
	[ "mysterious thing", "kawarith", "1" ],
	[ "need", "you", "1" ],
	[ "never", "neda", "1" ],
	[ "new", "nec", "1" ],
	[ "not", "noh", "1" ],
	[ "nothing", "nohden", "1" ],
	[ "now", "kep", "1" ],
	[ "objective", "keloonet", "1" ],
	[ "obsolete", "edos", "1" ],
	[ "on own", "sulee", "1" ],
	[ "one", "a", "1" ],
	[ "only", "pun", "1" ],
	[ "or", "doh", "1" ],
	[ "originally", "yeness", "1" ],
	[ "outside", "sh'yan", "1" ],
	[ "pardon", "tay", "1" ],
	[ "part", "boon", "1" ],
	[ "people / beings", "Diet", "1" ],
	[ "place", "a'dam", "1" ],
	[ "please", "tzair (qie)", "1" ],
	[ "possible", "ha-ay", "1" ],
	[ "pray", "thoon", "1" ],
	[ "prayer", "thoona", "1" ],
	[ "protect", "sheshte", "1" ],
	[ "put (to be)", "laysht", "1" ],
	[ "put away", "dama", "1" ],
	[ "reach", "ar", "1" ],
	[ "reality", "bess", "1" ],
	[ "reason", "ray'en", "1" ],
	[ "remember", "keet", "1" ],
	[ "rest", "sootay", "1" ],
	[ "safe", "cosh", "1" ],
	[ "same", "coht", "1" ],
	[ "say", "kon", "1" ],
	[ "see", "air(ghgh)", "1" ],
	[ "separate", "n'adoh", "1" ],
	[ "shadows", "shakay", "1" ],
	[ "shelter", "yada", "1" ],
	[ "small", "co", "1" ],
	[ "soul", "san", "1" ],
	[ "soup", "moy", "1" ],
	[ "spirits", "espa", "1" ],
	[ "stay", "tay(4)", "1" ],
	[ "still", "hay", "1" ],
	[ "stray", "you-een", "1" ],
	[ "strong", "oss", "1" ],
	[ "take (ba3)", "ban", "1" ],
	[ "tangible", "Geyan", "1" ],
	[ "tell", "gaw", "1" ],
	[ "thank you", "(t)zay", "1" ],
	[ "that", "keta", "1" ],
	[ "there", "kona", "1" ],
	[ "thing / essence", "den", "1" ],
	[ "think", "kwuun", "1" ],
	[ "this", "ket", "1" ],
	[ "time", "tem", "1" ],
	[ "tired", "la-eyn", "1" ],
	[ "to be*", "sool", "1" ],
	[ "today", "kyo", "1" ],
	[ "together", "a'doh", "1" ],
	[ "too", "gun", "1" ],
	[ "treat (dui4)", "dway", "1" ],
	[ "true true", "vay", "1" ],
	[ "trust", "solu", "1" ],
	[ "truth", "vay", "1" ],
	[ "try", "nnn", "1" ],
	[ "two", "doh", "1" ],
	[ "understand", "e'kwuun", "1" ],
	[ "upstairs", "tahnk", "1" ],
	[ "very", "gun", "1" ],
	[ "wait", "doon", "1" ],
	[ "wall", "ta'k-ray", "1" ],
	[ "want", "yurn", "1" ],
	[ "way (yang4zi)", "lang", "1" ],
	[ "what?", "son?", "1" ],
	[ "what's wrong?", "lutayboo", "1" ],
	[ "where?", "don?", "1" ],
	[ "who?", "soo", "1" ],
	[ "whole", "awool", "1" ],
	[ "why?", "kai", "1" ],
	[ "will (of god)", "we", "1" ],
	[ "wish", "zetheen", "1" ],
	[ "with (gen)", "tan", "1" ],
	[ "within/inside", "inos", "1" ],
	[ "wonderful", "jee-er", "1" ],
	[ "words", "zell", "1" ],
	[ "world / universe", "awoosk", "1" ],
	[ "wrong", "tayboo", "1" ],
	[ "yes", "yat", "1" ],
	[ "zero", "ash", "1" ]
];

